// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/patient-fyd/jxust-softhub-api/internal/logic/middleware"
)
