// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/patient-fyd/jxust-softhub-api/internal/logic/middleware"
	_ "github.com/patient-fyd/jxust-softhub-api/internal/logic/auth"
	_ "github.com/patient-fyd/jxust-softhub-api/internal/logic/member"
	_ "github.com/patient-fyd/jxust-softhub-api/internal/logic/post"
	_ "github.com/patient-fyd/jxust-softhub-api/internal/logic/comment"
	_ "github.com/patient-fyd/jxust-softhub-api/internal/logic/like"
	_ "github.com/patient-fyd/jxust-softhub-api/internal/logic/follow"
	_ "github.com/patient-fyd/jxust-softhub-api/internal/logic/circle"
)
