// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalActivityRegistrationsDao is internal type for wrapping internal DAO implements.
type internalActivityRegistrationsDao = *internal.ActivityRegistrationsDao

// activityRegistrationsDao is the data access object for table activity_registrations.
// You can define custom methods on it to extend its functionality as you wish.
type activityRegistrationsDao struct {
	internalActivityRegistrationsDao
}

var (
	// ActivityRegistrations is globally public accessible object for table activity_registrations operations.
	ActivityRegistrations = activityRegistrationsDao{
		internal.NewActivityRegistrationsDao(),
	}
)

// Fill with you ideas below.
