// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalActivitiesDao is internal type for wrapping internal DAO implements.
type internalActivitiesDao = *internal.ActivitiesDao

// activitiesDao is the data access object for table activities.
// You can define custom methods on it to extend its functionality as you wish.
type activitiesDao struct {
	internalActivitiesDao
}

var (
	// Activities is globally public accessible object for table activities operations.
	Activities = activitiesDao{
		internal.NewActivitiesDao(),
	}
)

// Fill with you ideas below.
