// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalAuditLogsDao is internal type for wrapping internal DAO implements.
type internalAuditLogsDao = *internal.AuditLogsDao

// auditLogsDao is the data access object for table audit_logs.
// You can define custom methods on it to extend its functionality as you wish.
type auditLogsDao struct {
	internalAuditLogsDao
}

var (
	// AuditLogs is globally public accessible object for table audit_logs operations.
	AuditLogs = auditLogsDao{
		internal.NewAuditLogsDao(),
	}
)

// Fill with you ideas below.
