// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalBlogsDao is internal type for wrapping internal DAO implements.
type internalBlogsDao = *internal.BlogsDao

// blogsDao is the data access object for table blogs.
// You can define custom methods on it to extend its functionality as you wish.
type blogsDao struct {
	internalBlogsDao
}

var (
	// Blogs is globally public accessible object for table blogs operations.
	Blogs = blogsDao{
		internal.NewBlogsDao(),
	}
)

// Fill with you ideas below.
