// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalBlogLikesDao is internal type for wrapping internal DAO implements.
type internalBlogLikesDao = *internal.BlogLikesDao

// blogLikesDao is the data access object for table blog_likes.
// You can define custom methods on it to extend its functionality as you wish.
type blogLikesDao struct {
	internalBlogLikesDao
}

var (
	// BlogLikes is globally public accessible object for table blog_likes operations.
	BlogLikes = blogLikesDao{
		internal.NewBlogLikesDao(),
	}
)

// Fill with you ideas below.
