// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalBlogCommentsDao is internal type for wrapping internal DAO implements.
type internalBlogCommentsDao = *internal.BlogCommentsDao

// blogCommentsDao is the data access object for table blog_comments.
// You can define custom methods on it to extend its functionality as you wish.
type blogCommentsDao struct {
	internalBlogCommentsDao
}

var (
	// BlogComments is globally public accessible object for table blog_comments operations.
	BlogComments = blogCommentsDao{
		internal.NewBlogCommentsDao(),
	}
)

// Fill with you ideas below.
