// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalCirclesDao is internal type for wrapping internal DAO implements.
type internalCirclesDao = *internal.CirclesDao

// circlesDao is the data access object for table circles.
// You can define custom methods on it to extend its functionality as you wish.
type circlesDao struct {
	internalCirclesDao
}

var (
	// Circles is globally public accessible object for table circles operations.
	Circles = circlesDao{
		internal.NewCirclesDao(),
	}
)

// Fill with you ideas below.
