// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalJoinApplicationsDao is internal type for wrapping internal DAO implements.
type internalJoinApplicationsDao = *internal.JoinApplicationsDao

// joinApplicationsDao is the data access object for table join_applications.
// You can define custom methods on it to extend its functionality as you wish.
type joinApplicationsDao struct {
	internalJoinApplicationsDao
}

var (
	// JoinApplications is globally public accessible object for table join_applications operations.
	JoinApplications = joinApplicationsDao{
		internal.NewJoinApplicationsDao(),
	}
)

// Fill with you ideas below.
