// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalNewsDao is internal type for wrapping internal DAO implements.
type internalNewsDao = *internal.NewsDao

// newsDao is the data access object for table news.
// You can define custom methods on it to extend its functionality as you wish.
type newsDao struct {
	internalNewsDao
}

var (
	// News is globally public accessible object for table news operations.
	News = newsDao{
		internal.NewNewsDao(),
	}
)

// Fill with you ideas below.
