// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalPostsDao is internal type for wrapping internal DAO implements.
type internalPostsDao = *internal.PostsDao

// postsDao is the data access object for table posts.
// You can define custom methods on it to extend its functionality as you wish.
type postsDao struct {
	internalPostsDao
}

var (
	// Posts is globally public accessible object for table posts operations.
	Posts = postsDao{
		internal.NewPostsDao(),
	}
)

// Fill with you ideas below.
