// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalPostImagesDao is internal type for wrapping internal DAO implements.
type internalPostImagesDao = *internal.PostImagesDao

// postImagesDao is the data access object for table postImages.
// You can define custom methods on it to extend its functionality as you wish.
type postImagesDao struct {
	internalPostImagesDao
}

var (
	// PostImages is globally public accessible object for table postImages operations.
	PostImages = postImagesDao{
		internal.NewPostImagesDao(),
	}
)

// Fill with you ideas below.
