// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalProjectsDao is internal type for wrapping internal DAO implements.
type internalProjectsDao = *internal.ProjectsDao

// projectsDao is the data access object for table projects.
// You can define custom methods on it to extend its functionality as you wish.
type projectsDao struct {
	internalProjectsDao
}

var (
	// Projects is globally public accessible object for table projects operations.
	Projects = projectsDao{
		internal.NewProjectsDao(),
	}
)

// Fill with you ideas below.
