// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalSystemConfigsDao is internal type for wrapping internal DAO implements.
type internalSystemConfigsDao = *internal.SystemConfigsDao

// systemConfigsDao is the data access object for table system_configs.
// You can define custom methods on it to extend its functionality as you wish.
type systemConfigsDao struct {
	internalSystemConfigsDao
}

var (
	// SystemConfigs is globally public accessible object for table system_configs operations.
	SystemConfigs = systemConfigsDao{
		internal.NewSystemConfigsDao(),
	}
)

// Fill with you ideas below.
