// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/patient-fyd/jxust-softhub-api/internal/dao/internal"
)

// internalVisitStatisticsDao is internal type for wrapping internal DAO implements.
type internalVisitStatisticsDao = *internal.VisitStatisticsDao

// visitStatisticsDao is the data access object for table visit_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type visitStatisticsDao struct {
	internalVisitStatisticsDao
}

var (
	// VisitStatistics is globally public accessible object for table visit_statistics operations.
	VisitStatistics = visitStatisticsDao{
		internal.NewVisitStatisticsDao(),
	}
)

// Fill with you ideas below.
